-- Nucleus Concierge — Phase 2 seed data (demo paths: researcher, operator, student; investor stretch).
-- pgvector: embeddings are NULL until you run `deno run -A supabase/scripts/backfill-embeddings.ts` (OPENAI_API_KEY + Supabase service role env).
--
-- Admin bootstrap:
--   • Preferred: `/admin/signup` in the app + confirm email when required → trigger creates `admin_users`.
--   • Manual Dashboard user: still works; AFTER INSERT trigger also adds `admin_users` (unless row exists).

-- ---------------------------------------------------------------------------
-- Seed people (mix of person_types for matching demos; obvious fake contacts)
-- ---------------------------------------------------------------------------
insert into public.people (
  id,
  first_name,
  last_name,
  email,
  organization,
  title,
  bio,
  person_types,
  sectors,
  skills,
  availability,
  stage_preferences,
  engagement_preferences,
  source,
  status,
  embedding_text
) values
(
  'a1000000-0000-4000-8000-000000000001',
  'Jordan',
  'Ellis',
  'jordan.ellis.demo@nucleus.local',
  'Wasatch Commercialization Collective',
  'Commercialization mentor',
  'Former life-sciences operator; helps faculty turn lab-validated diagnostics into viable products. Focus on early market conversations and licensing vs spinout decisions.',
  array['mentor', 'advisor', 'operator']::text[],
  array['life_sciences', 'diagnostics', 'medical_devices']::text[],
  array['regulatory_pathways', 'tech_transfer', 'customer_discovery', 'pitch']::text[],
  array['fractional', 'project_based']::text[],
  array['lab_validated', 'pre_seed', 'seed']::text[],
  array['mentoring', 'advisory', 'one_off_calls']::text[],
  'seed',
  'active',
  'Mentor commercialization diagnostics life sciences tech transfer Utah'
),
(
  'a1000000-0000-4000-8000-000000000002',
  'Samira',
  'Nour',
  'samira.nour.demo@nucleus.local',
  'Regulus Regulatory Advisory',
  'Regulatory strategist (IVD / SaMD)',
  'Helps diagnostic and SaMD teams map FDA strategy, quality systems, and clinical evidence plans without over-building for the wrong pathway.',
  array['expert', 'advisor']::text[],
  array['life_sciences', 'diagnostics', 'digital_health']::text[],
  array['FDA', 'IVD', 'ISO13485', 'clinical_evidence']::text[],
  array['advisory', 'project_based']::text[],
  array['pre_seed', 'seed', 'series_a']::text[],
  array['short_projects', 'advisory']::text[],
  'seed',
  'active',
  'Regulatory advisor diagnostics SaMD IVD FDA Utah remote'
),
(
  'a1000000-0000-4000-8000-000000000003',
  'Alex',
  'Vega',
  'alex.vega.demo@nucleus.local',
  'Nucleus Student Discovery Studio',
  'Grad student lead — discovery sprints',
  'Runs structured 2-week discovery sprints with university teams: interviews, market sizing snapshots, and recommendation memos for mentors and PIs.',
  array['student', 'researcher']::text[],
  array['deeptech', 'life_sciences', 'software']::text[],
  array['customer_interviews', 'market_research', 'memo_writing']::text[],
  array['part_time', 'project_based']::text[],
  array['lab_validated', 'mvp']::text[],
  array['internship', 'project_work']::text[],
  'seed',
  'active',
  'Student discovery team market research interviews memos'
),
(
  'a1000000-0000-4000-8000-000000000004',
  'Chris',
  'Bakken',
  'chris.bakken.demo@nucleus.local',
  'Independent',
  'Fractional COO / ops',
  'Manufacturing and ops leadership for early-stage hardware and regulated products. Prefers Utah-based or Mountain West teams with lab-to-pilot milestones.',
  array['operator', 'executive']::text[],
  array['manufacturing', 'hardware', 'industrial']::text[],
  array['ops', 'supply_chain', 'quality', 'scaling']::text[],
  array['fractional', 'part_time']::text[],
  array['seed', 'series_a']::text[],
  array['fractional_exec', 'project_based']::text[],
  'seed',
  'active',
  'Fractional COO manufacturing Utah startup operations supply chain'
),
(
  'a1000000-0000-4000-8000-000000000005',
  'Dr. Morgan',
  'Iwata',
  'morgan.iwata.demo@nucleus.local',
  'State U. Bioengineering',
  'Professor — tissue engineering',
  'Principal investigator with several publications; exploring whether IP should license or spin out. Looking for honest commercialization guidance.',
  array['researcher', 'founder']::text[],
  array['life_sciences', 'tissue_engineering']::text[],
  array['grants', 'tech_transfer', 'patents']::text[],
  array['advisory', 'exploratory']::text[],
  array['lab_validated']::text[],
  array['mentoring', 'exploratory_calls']::text[],
  'seed',
  'active',
  'Professor researcher tissue engineering tech transfer patents'
),
(
  'a1000000-0000-4000-8000-000000000006',
  'Riley',
  'Nguyen',
  'riley.nguyen.demo@nucleus.local',
  'HelioSpec Labs',
  'Founder / CEO',
  'Spectral sensing startup for industrial quality control; raising seed and hiring first ops lead.',
  array['founder', 'executive']::text[],
  array['industrial', 'hardware', 'deeptech']::text[],
  array['fundraising', 'gtm', 'hiring']::text[],
  array['full_time']::text[],
  array['seed']::text[],
  array['hiring', 'investor_conversations']::text[],
  'seed',
  'active',
  'Founder CEO seed hardware industrial sensing Utah hiring'
),
(
  'a1000000-0000-4000-8000-000000000007',
  'Priya',
  'Malhotra',
  'priya.malhotra.demo@nucleus.local',
  'CrossRange Ventures',
  'Angel / early-stage investor',
  'Focused on Mountain West B2B and health-adjacent tools; writes small checks and makes targeted intros.',
  array['investor']::text[],
  array['b2b_saas', 'healthcare_it', 'industrial']::text[],
  array['due_diligence', 'board_observer', 'intros']::text[],
  array['advisory']::text[],
  array['pre_seed', 'seed']::text[],
  array['deal_flow', 'curated_intros']::text[],
  'seed',
  'active',
  'Angel investor seed Mountain West B2B healthcare intros due diligence'
),
(
  'a1000000-0000-4000-8000-000000000008',
  'Taylor',
  'Brooks',
  'taylor.brooks.demo@nucleus.local',
  'Campus Venture Law Group',
  'Attorney — startup formation / IP basics',
  'Formation, founder equity, and lightweight IP strategy for university spinouts.',
  array['service_provider', 'advisor']::text[],
  array['legal', 'spinouts', 'university']::text[],
  array['incorporation', 'founder_agreements', 'ip_assignment']::text[],
  array['project_based']::text[],
  array['pre_seed', 'seed']::text[],
  array['fixed_fee_packages']::text[],
  'seed',
  'active',
  'Startup attorney formation equity university spinout Utah'

);

-- ---------------------------------------------------------------------------
-- Seed opportunities (several type values — Section 9.5)
-- ---------------------------------------------------------------------------
insert into public.opportunities (
  id,
  name,
  type,
  description,
  organization,
  sector,
  stage,
  need_types,
  status,
  source,
  embedding_text
) values
(
  'b2000000-0000-4000-8000-000000000001',
  'Diagnostic spinout — regulatory navigation',
  'startup_need',
  'Lab-validated diagnostics team needs regulatory pathway clarity and intro to quality advisors before first pilot conversations.',
  'Benchlight Dx',
  array['life_sciences', 'diagnostics']::text[],
  'lab_validated',
  array['regulatory', 'mentorship', 'operator']::text[],
  'active',
  'seed',
  'Startup need diagnostics regulatory lab validated Utah commercialization'
),
(
  'b2000000-0000-4000-8000-000000000002',
  'Campus IP — licensing vs company',
  'research_project',
  'Tissue engineering portfolio decision: evaluate licensing partners vs forming a newCo; needs experienced commercialization mentor.',
  'State U. Tech Transfer',
  array['life_sciences', 'tissue_engineering']::text[],
  'grant_funded',
  array['mentorship', 'licensing', 'market_analysis']::text[],
  'active',
  'seed',
  'Research project tech transfer licensing tissue engineering mentor'
),
(
  'b2000000-0000-4000-8000-000000000003',
  'Discovery sprint cohort — Winter',
  'program',
  'Student-led discovery cohort for 6 faculty projects; produces interview summaries and competitor snapshots.',
  'Nucleus Student Discovery Studio',
  array['deeptech', 'life_sciences']::text[],
  'open',
  array['students', 'market_research']::text[],
  'active',
  'seed',
  'Program student discovery cohort market research interviews'
),
(
  'b2000000-0000-4000-8000-000000000004',
  'HelioSpec — fractional ops hire',
  'advisory_need',
  'Seed-stage sensing company needs fractional ops leader to tighten supplier onboarding and pilot execution.',
  'HelioSpec Labs',
  array['hardware', 'industrial']::text[],
  'seed',
  array['operator', 'fractional']::text[],
  'active',
  'seed',
  'Advisory need fractional operations manufacturing seed startup Utah'
),
(
  'b2000000-0000-4000-8000-000000000005',
  'Internship — GTM research (3 months)',
  'internship',
  'Part-time internship supporting two founders with structured customer discovery in industrial buyers.',
  'CrossCut Analytics',
  array['b2b', 'analytics']::text[],
  'mvp',
  array['students', 'gtm']::text[],
  'active',
  'seed',
  'Internship student go to market research industrial B2B'
),
(
  'b2000000-0000-4000-8000-000000000006',
  'Mountain West — curated seed dealflow',
  'investor_opportunity',
  'Quarterly curated intros for B2B pre-seed and seed teams with early revenue or credible pilots.',
  'Nucleus Connections Hub',
  array['b2b', 'healthcare_it', 'industrial']::text[],
  'multi_stage',
  array['investor_intros', 'deal_flow']::text[],
  'active',
  'seed',
  'Investor opportunity seed deal flow Mountain West curated intros'
),
(
  'b2000000-0000-4000-8000-000000000007',
  'Service need — spinout formation package',
  'service_need',
  'Lightweight legal + cap table setup for a newCo path out of a university lab.',
  'Benchlight Dx',
  array['legal', 'spinouts']::text[],
  'formation',
  array['legal', 'incorporation']::text[],
  'active',
  'seed',
  'Service need legal incorporation spinout university'
),
(
  'b2000000-0000-4000-8000-000000000008',
  'Mentorship — first-time faculty founders',
  'mentorship_need',
  'PI with strong publication record seeking mentor for first customer discovery cycle and pitch practice.',
  'State U. Bioengineering',
  array['life_sciences']::text[],
  'lab_validated',
  array['mentorship', 'customer_discovery']::text[],
  'active',
  'seed',
  'Mentorship need professor commercialization customer discovery'
);
